<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <title>Layui - 经典模块化前端 UI 框架</title>
    <meta name="keywords" content="layui,ui,ui框架,前端框架,JS组件">
    <meta name="description"
          content="layui 是一款采用自身模块规范编写的前端 UI 框架，遵循原生 HTML/CSS/JS 的书写与组织形式，门槛极低，拿来即用。其外在极简，却又不失饱满的内在，体积轻盈，组件丰盈，从核心代码到 API 的每一处细节都经过精心雕琢，非常适合界面的快速开发。">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="format-detection" content="telephone=no">

    <link rel="stylesheet" href="/component/layui/css/layui.css" media="all">
    <link id="layuicss-skincodecss" rel="stylesheet" href="/component/layui/css/modules/code.css"
          media="all">
    <link id="layuicss-layer" rel="stylesheet" href="/component/layui/css/modules/layer/default/layer.css"
          media="all">
</head>
<body class="site-home" id="LAY_home" style="background-color: #eee;" data-date="12-6">
<div class="layui-header header header-index" winter1="">
    <div class="layui-main">
        <a class="layui-nav-img" href="/">
<!--            <img src="/favicon.ico" alt="layui">-->
        </a>
        <div class="layui-form component" lay-filter="LAY-site-header-component">
            <div class="layui-form-select">
                <div class="layui-select-title">
                    <input type="text" placeholder="搜索组件或模块" value="" class="layui-input">
                    <i class="layui-edge"></i>
                </div>
            </div>
        </div>
        <ul class="layui-nav">
            <li class="layui-nav-item ">
                <a href="/doc/">文档<!-- <span class="layui-badge-dot"></span> --></a>
            </li>
            <li class="layui-nav-item ">
                <a href="/demo/">示例<!-- <span class="layui-badge-dot"></span> --></a>
            </li>


            <li class="layui-nav-item layui-hide-xs">
                <a href="//fly.layui.com/" target="_blank">社区</a>
            </li>

            <li class="layui-nav-item">
                <a href="javascript:;">
                    <!--<span class="layui-badge-dot" style="left:0; right: auto; margin: -4px 0 0 5px;"></span>-->
                    周边<span class="layui-nav-more"></span></a>
                <dl class="layui-nav-child layui-anim layui-anim-upbit"
                    style="left: auto; right: -22px; text-align: center;">
                    <dd lay-unselect="">
                        <a href="//fly.layui.com/extend/" target="_blank">扩展组件</a>
                    </dd>
                    <dd lay-unselect="">
                        <a href="//fly.layui.com/store/" target="_blank">模板市场</a>
                        <hr>
                    </dd>

                    <dd class="layui-hide-sm layui-show-xs" lay-unselect="">
                        <a href="//fly.layui.com/" target="_blank">社区交流</a>
                        <hr>
                    </dd>
                    <dd lay-unselect=""><a href="/admin/" target="_blank">后台模板 <span class="layui-badge-dot"
                                                                                     style="margin-top: -5px;"></span></a>
                    </dd>
                    <dd lay-unselect=""><a href="/layim/" target="_blank">即时聊天</a>
                        <hr>
                    </dd>

                    <dd lay-unselect=""><a href="/alone.html" target="_blank" lay-unselect="">独立组件</a></dd>
                    <dd lay-unselect=""><a href="https://fly.layui.com/jie/24209/" target="_blank">Axure 组件</a>
                        <hr>
                    </dd>

                    <dd lay-unselect="">
                        <a href="https://www.layuicdn.com/?from=layui" target="_blank" id="layui-spm-event-layuicdn"
                           rel="nofollow">
                            layui cdn
                        </a>
                    </dd>
                    <!--<dd lay-unselect>
                      <a href="https://www.xiankefu.com/" target="_blank" id="layui-spm-event-zb-xiankefu">客服系统 <span class="layui-badge-dot" style="margin-top: -5px;"></span></a>
                    </dd>-->
                    <!--<dd lay-unselect>
                      <a href="https://fly.layui.com/jump/201911/" target="_blank" id="layui-spm-event-aliyun">阿里云特惠 <span class="layui-badge-dot" style="margin-top: -5px;"></span></a>
                    </dd>-->
                </dl>
            </li>


            <li class="layui-nav-item layui-hide-xs" lay-unselect="">
                <a href="https://fly.layui.com/jump/alyhot/" target="_blank" id="layui-spm-event-parter">阿里云双12 <span
                            class="layui-badge-dot" style="margin-top: -5px;"></span></a>
            </li>


            <li class="layui-nav-item layui-hide-xs" lay-unselect="">
                <a href="/admin/" target="_blank">后台模板 <span class="layui-badge-dot"
                                                             style="margin-top: -5px;"></span></a>
            </li>
            <span class="layui-nav-bar" style="left: 378px; top: 55px; width: 0px; opacity: 0;"></span></ul>
    </div>
</div>
<script src="/component/layui/layui.js"></script>
</body>

